apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/neviadomski/argocd-config.git
    path: infrastructure/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true